---
- name: create_host_group
  hosts: localhost
  gather_facts: no
  
  vars:
    ip_address: "{{ survey_ip }}"  
  
  tasks:
  - name: make host group from ip provided in survey
    add_host:
      hostname: "{{ ip_address }}"
      groupname: tmp_group      
  - debug:
      msg: "created host group tmp_group with host {{ ip_address }}"
