---
- name: configure inventory host
  hosts: localhost
  gather_facts: no
  
  vars:
    ip_address: "{{ survey_ip }}"  
  
  tasks:
  - name: make host group from ip provided in survey
    add_host:
      hostname: "{{ ip_address }}"
      groupname: new_group      

- name: verify basic accessibility
  hosts: new_group,!localhost
  gather_facts: no
  become: true
  
  tasks:
  - action: ping
