---
- name: Create host group with single IP fetched from survey input
  hosts: localhost
  gather_facts: no
  
  vars:
    ip_address: "{{ survey_ip }}"  
  
  tasks:
  - name: Create temp host group from ip provided in survey
    add_host:
      hostname: "{{ ip_address }}"
      groupname: tmp_group      

- name: Verify basic accessibility of VM
  hosts: tmp_group,!localhost
  gather_facts: no
  become: true
  
  tasks:
  - action: ping

- name: Setup aklops user
  hosts: tmp_group,!localhost
  gather_facts: no
  
  tasks:
  - name: Set up aklops account         
    user:
      name: aklops
      create_home: yes
      shell: /bin/bash
      expires: -1
      
  - name: Add public key to authorized_keys file
    authorized_key:
      user: aklops
      state: present
      key: {{ aklops_public_key }}

  - name: Allow aklops user to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^aklops'
      line: 'aklops ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

- name: Tag Nectar VM as set up
  hosts: tmp_group,!localhost
  gather_facts: no
  
  tasks:
  - debug:
     msg: "tagging nectar vm"
